### ISSUE TITLE
gap function doesn't work ?

### ISSUE THREAD

**Issue by TomasBalbinder** [gilbitron/flexmasonry#16]
Hello, I apologize, but I am trying to add a gap between objects but still doesn't work. is the gap created at all? 
Thank you so much 

![image](https://user-images.githubusercontent.com/55196762/218610714-762c33e4-5be1-44de-89ef-ecf937eacdd9.png)

**Comment by carlwafe** [comment]
Put your pictures in a div container that has a few pixels padding, that should do the trick.

**Comment by TomasBalbinder** [comment]
I'm sorry, but I don't understand, I've tried almost everything

**Comment by TomasBalbinder** [comment]
![image](https://user-images.githubusercontent.com/55196762/218727707-339f97cc-213b-41e3-a4ab-b82ce297b33e.png)
doesn't work or I don't understand sorry

**Comment by TomasBalbinder** [comment]
hi, solved I use parent div on element with padding.
